# Generated by Django 5.0.4 on 2024-04-29 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0003_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_points",
                to="core_app.team",
            ),
        ),
    ]
