# Generated by Django 5.0.4 on 2024-05-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0004_alter_point_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="mgrs",
            field=models.TextField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
