# Generated by Django 5.0.4 on 2024-05-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0005_point_mgrs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="point",
            name="mgrs",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
