# Generated by Django 5.0.4 on 2024-05-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0007_alter_point_mgrs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
